### ISSUE TITLE
Tests are failing with Jest using CRA

### ISSUE THREAD

**Issue by RusinovAnton** [medipass/react-credit-card-input#29]
Test suite failed to run
Cannot find module 'react' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous>.React__default (../node_modules/react-credit-card-input/lib/index.js:2:90)
      at Object.<anonymous> (../node_modules/react-credit-card-input/lib/index.js:5:2)

**Comment by jxom** [comment]
React is a peer dependency of react-credit-card-input, so I don't think it's related to this package, and Medipass has managed to get tests working well with this library (using Jest and CRA). Is react listed in your node_modules/ folder?

**Comment by RusinovAnton** [comment]
>  Is react listed in your node_modules/ folder?

Yes it is. Also both dev and prod build are successful. 
Can't figure out why this error occurs during tests. I was hoping that someone may have similar problems and can help me to figure this out.
